version: ~> 1.0
language: generic
os: linux
dist: bionic
jobs:
  include:
  - name: "Fedora 31 (Docker) with Python 3.7"
    env: FEDORA_VERSION="31"
    group: edge
    language: python
    python: 3.7
    services:
    - docker
  - name: "Fedora 32 (Docker) with Python 3.8"
    env: FEDORA_VERSION="32"
    group: edge
    language: python
    python: 3.8
    services:
    - docker
  - name: "Ubuntu Bionic (18.04) (Docker) with Python 3.6"
    env: UBUNTU_VERSION="18.04"
    group: edge
    language: python
    python: 3.6
    services:
    - docker
  - name: "Ubuntu Focal (20.04) (Docker) with Python 3.8"
    env: UBUNTU_VERSION="20.04"
    group: edge
    language: python
    python: 3.8
    services:
    - docker
  - name: "Ubuntu Focal (20.04) (Docker) with Python 3.6 (tox)"
    env:
    - TOXENV="py36"
    - UBUNTU_VERSION="20.04"
    group: edge
    language: python
    python: 3.6
    services:
    - docker
  - name: "Ubuntu Focal (20.04) (Docker) with Python 3.7 (tox)"
    env:
    - TOXENV="py37"
    - UBUNTU_VERSION="20.04"
    group: edge
    language: python
    python: 3.7
    services:
    - docker
  - name: "Ubuntu Focal (20.04) (Docker) with Python 3.8 (tox)"
    env:
    - TOXENV="py38,coverage,codecov"
    - UBUNTU_VERSION="20.04"
    group: edge
    language: python
    python: 3.8
    services:
    - docker
  - name: "Sphinx on Ubuntu Focal (20.04) (Docker) with Python 3.8 (tox)"
    env:
    - TOXENV="docs"
    - UBUNTU_VERSION="20.04"
    group: edge
    language: python
    python: 3.8
    services:
    - docker
  - name: "Pylint on Ubuntu Focal (20.04) (Docker) with Python 3.8 (tox)"
    env:
    - TOXENV="pylint"
    - UBUNTU_VERSION="20.04"
    group: edge
    language: python
    python: 3.8
    services:
    - docker
  - name: "MacOS 10.14 with Python 3.8 (tox)"
    env: TOXENV="py38"
    os: osx
    osx_image: xcode11
  - name: "Dockerfile"
    env: TARGET="dockerfile"
    group: edge
  - name: "Jenkins on Ubuntu Bionic (18.04) (Docker) with Python 3.6"
    env: [TARGET="jenkins3", UBUNTU_VERSION="18.04"]
    group: edge
    language: python
    python: 3.6
    services:
    - docker
install:
- ./config/travis/install.sh
script:
- ./config/travis/run_with_timeout.sh 45 ./config/travis/runtests.sh
