language: python
python:
  - "2.7"
before_install:
  - sudo add-apt-repository ppa:kristinn-l/plaso-dev -y
  - sudo apt-get update -q
  - sudo apt-get install binplist libbde-python libesedb-python libevt-python libevtx-python libewf-python libfwsi-python liblnk-python libmsiecf-python libolecf-python libqcow-python libregf-python libsmdev-python libsmraw-python libvhdi-python libvmdk-python libvshadow-python ipython python-bencode python-construct python-dateutil python-dfvfs python-dpkt python-hachoir-core python-hachoir-metadata python-hachoir-parser python-protobuf python-psutil python-pyparsing python-six python-yaml python-tz pytsk3
  - sudo pip install coveralls
  - sudo pip install ipython
script:
  - ./run_tests.py
  - coverage run --source=plaso --omit="*_test*,*__init__*,*test_lib*" ./run_tests.py
after_success:
  - coveralls
