matrix:
  include:
  - name: "Pylint on Ubuntu Bionic (18.04) (Docker) with Python 3.6"
    env: [TARGET="pylint", UBUNTU_VERSION="18.04"]
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.6
    services:
    - docker
  - name: "Ubuntu Xenial (16.04) with Python 2.7"
    env: TARGET="linux-python27"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 2.7
    virtualenv:
      system_site_packages: true
  - name: "Ubuntu Xenial (16.04) with Python 3.5"
    env: TARGET="linux-python35"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.5
    virtualenv:
      system_site_packages: true
  - name: "Fedora Core 29 (Docker) with Python 2.7"
    env: FEDORA_VERSION="29"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 2.7
    services:
    - docker
  - name: "Fedora Core 29 (Docker) with Python 3.7"
    env: FEDORA_VERSION="29"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.7
    services:
    - docker
  - name: "Ubuntu Bionic (18.04) (Docker) with Python 2.7"
    env: UBUNTU_VERSION="18.04"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 2.7
    services:
    - docker
  - name: "Ubuntu Bionic (18.04) (Docker) with Python 3.6"
    env: UBUNTU_VERSION="18.04"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.6
    services:
    - docker
  - name: "Ubuntu Bionic (18.04) (Docker) with Python 2.7 and tox"
    env: [TOXENV="py27", UBUNTU_VERSION="18.04"]
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 2.7
    services:
    - docker
  - name: "Ubuntu Bionic (18.04) (Docker) with Python 3.4 and tox"
    env: [TOXENV="py34", UBUNTU_VERSION="18.04"]
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.4
    services:
    - docker
  - name: "Ubuntu Bionic (18.04) (Docker) with Python 3.5 and tox"
    env: [TOXENV="py35", UBUNTU_VERSION="18.04"]
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.5
    services:
    - docker
  - name: "Ubuntu Bionic (18.04) (Docker) with Python 3.6 and tox"
    env: [TOXENV="py36", UBUNTU_VERSION="18.04"]
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.6
    services:
    - docker
  - name: "Ubuntu Bionic (18.04) (Docker) with Python 3.7 and tox"
    env: [TOXENV="py37", UBUNTU_VERSION="18.04"]
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.7
    services:
    - docker
  - name: "MacOS with Python 2.7.10"
    env: [TARGET="macos-python27", PYTHONPATH="/Library/Python/2.7/site-packages/"]
    os: osx
    osx_image: xcode9.2
    language: generic
  - env: TARGET="jenkins3"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    python: 3.5
  - env: TARGET="jenkins2"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    python: 2.7
install:
- ./config/travis/install.sh
script:
- ./config/travis/run_with_timeout.sh 30 ./config/travis/runtests.sh
after_success:
- if ! test -f /usr/bin/coverage; then sudo ln -s /usr/bin/python-coverage /usr/bin/coverage; fi
- if test ${TARGET} = "linux-python27"; then curl -o codecov.sh -s https://codecov.io/bash && /bin/bash ./codecov.sh; fi
